on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: backend - unit tests
jobs:
  run:
    timeout-minutes: 5
    strategy:
      matrix:
        go-version: [ '1.23.x' ]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: run unit tests
        working-directory: backend
        run: make test
